[2024-11-27T16:15:55.143+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-27T16:15:55.192+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-27T11:30:00+00:00 [queued]>
[2024-11-27T16:15:55.220+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-27T11:30:00+00:00 [queued]>
[2024-11-27T16:15:55.220+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-11-27T16:15:55.265+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): save_data> on 2024-11-27 11:30:00+00:00
[2024-11-27T16:15:55.306+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-27T16:15:55.308+0000] {standard_task_runner.py:72} INFO - Started process 219 to run task
[2024-11-27T16:15:55.320+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelamento', 'save_data', 'scheduled__2024-11-27T11:30:00+00:00', '--job-id', '1684', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmp9iowsvf8']
[2024-11-27T16:15:55.321+0000] {standard_task_runner.py:105} INFO - Job 1684: Subtask save_data
[2024-11-27T16:15:55.455+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-27T11:30:00+00:00 [running]> on host 3de0f1e46a39
[2024-11-27T16:15:55.841+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelamento' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T11:30:00+00:00'
[2024-11-27T16:15:55.843+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-27T16:15:55.844+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-27T16:15:55.849+0000] {logging_mixin.py:190} INFO - Current task name:save_data state:running start_date:2024-11-27 16:15:55.192615+00:00
[2024-11-27T16:15:55.850+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelamento and current dag run status:running
[2024-11-27T16:15:55.850+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-27T16:15:55.851+0000] {inaturalist_dag.py:197} INFO - No new observations to store.
[2024-11-27T16:15:55.851+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-27T16:15:55.889+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-27T16:15:55.890+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=get_inaturalist_data_atropelamento, task_id=save_data, run_id=scheduled__2024-11-27T11:30:00+00:00, execution_date=20241127T113000, start_date=20241127T161555, end_date=20241127T161555
[2024-11-27T16:15:55.921+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-27T16:15:55.921+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-27T16:15:55.922+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelamento queued_at:2024-11-27 16:15:13.053326+00:00
[2024-11-27T16:15:55.922+0000] {logging_mixin.py:190} INFO - Task hostname:3de0f1e46a39 operator:_PythonDecoratedOperator
[2024-11-27T16:15:55.968+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-27T16:15:56.051+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T16:15:56.055+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
