[2024-12-03T12:19:04.953+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T12:19:04.988+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.publish_message_for_transformation manual__2024-12-03T12:16:48.884964+00:00 [queued]>
[2024-12-03T12:19:05.006+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.publish_message_for_transformation manual__2024-12-03T12:16:48.884964+00:00 [queued]>
[2024-12-03T12:19:05.007+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-12-03T12:19:05.047+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): publish_message_for_transformation> on 2024-12-03 12:16:48.884964+00:00
[2024-12-03T12:19:05.074+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=142) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T12:19:05.077+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2024-12-03T12:19:05.087+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_roadkill', 'publish_message_for_transformation', 'manual__2024-12-03T12:16:48.884964+00:00', '--job-id', '2142', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmp_057qf5v']
[2024-12-03T12:19:05.089+0000] {standard_task_runner.py:105} INFO - Job 2142: Subtask publish_message_for_transformation
[2024-12-03T12:19:05.202+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_roadkill.publish_message_for_transformation manual__2024-12-03T12:16:48.884964+00:00 [running]> on host 629c168e87a3
[2024-12-03T12:19:05.423+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_roadkill' AIRFLOW_CTX_TASK_ID='publish_message_for_transformation' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T12:16:48.884964+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T12:16:48.884964+00:00'
[2024-12-03T12:19:05.426+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T12:19:05.428+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T12:19:05.429+0000] {logging_mixin.py:190} INFO - Current task name:publish_message_for_transformation state:running start_date:2024-12-03 12:19:04.988770+00:00
[2024-12-03T12:19:05.429+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_roadkill and current dag run status:running
[2024-12-03T12:19:05.431+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T12:19:05.480+0000] {channel.py:1080} WARNING - Received remote Channel.Close (406): "PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'environbit' in vhost '/': received 'false' but current is 'true'" on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f4f9f3e0d40> params=<ConnectionParameters host=192.168.30.21 port=30673 virtual_host=/ ssl=False>>>
[2024-12-03T12:19:05.483+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 216, in publish_message_for_transformation
    producer.publish_message(message=message_object)
  File "/opt/airflow/connectors/rabbitmq.py", line 31, in publish_message
    channel.queue_declare(queue=self.channel)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2524, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1357, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
pika.exceptions.ChannelClosedByBroker: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'environbit' in vhost '/': received 'false' but current is 'true'")
[2024-12-03T12:19:05.534+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-03T12:19:05.535+0000] {logging_mixin.py:190} INFO - Task start:2024-12-03 12:19:04.988770+00:00 end:2024-12-03 12:19:05.533576+00:00 duration:0.544806
[2024-12-03T12:19:05.536+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): publish_message_for_transformation> dag:<DAG: get_inaturalist_data_roadkill> dagrun:<DagRun get_inaturalist_data_roadkill @ 2024-12-03 12:16:48.884964+00:00: manual__2024-12-03T12:16:48.884964+00:00, state:running, queued_at: 2024-12-03 12:17:24.672470+00:00. externally triggered: True>
[2024-12-03T12:19:05.536+0000] {logging_mixin.py:190} INFO - Failure caused by (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'environbit' in vhost '/': received 'false' but current is 'true'")
[2024-12-03T12:19:05.537+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=get_inaturalist_data_roadkill, task_id=publish_message_for_transformation, run_id=manual__2024-12-03T12:16:48.884964+00:00, execution_date=20241203T121648, start_date=20241203T121904, end_date=20241203T121905
[2024-12-03T12:19:05.587+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T12:19:05.588+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2142 for task publish_message_for_transformation ((406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'environbit' in vhost '/': received 'false' but current is 'true'"); 152)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 216, in publish_message_for_transformation
    producer.publish_message(message=message_object)
  File "/opt/airflow/connectors/rabbitmq.py", line 31, in publish_message
    channel.queue_declare(queue=self.channel)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 2524, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "/home/airflow/.local/lib/python3.12/site-packages/pika/adapters/blocking_connection.py", line 1357, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
pika.exceptions.ChannelClosedByBroker: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'environbit' in vhost '/': received 'false' but current is 'true'")
[2024-12-03T12:19:05.670+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-03T12:19:05.692+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
