[2024-11-04T13:38:04.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T13:38:04.999+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-04T12:30:00+00:00 [queued]>
[2024-11-04T13:38:05.006+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-04T12:30:00+00:00 [queued]>
[2024-11-04T13:38:05.006+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-11-04T13:38:05.018+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): save_data> on 2024-11-04 12:30:00+00:00
[2024-11-04T13:38:05.027+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2728) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T13:38:05.029+0000] {standard_task_runner.py:72} INFO - Started process 2741 to run task
[2024-11-04T13:38:05.029+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelamento', 'save_data', 'scheduled__2024-11-04T12:30:00+00:00', '--job-id', '457', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmphvnecy1j']
[2024-11-04T13:38:05.030+0000] {standard_task_runner.py:105} INFO - Job 457: Subtask save_data
[2024-11-04T13:38:05.080+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelamento.save_data scheduled__2024-11-04T12:30:00+00:00 [running]> on host d6bcfe968a2b
[2024-11-04T13:38:05.201+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelamento' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T12:30:00+00:00'
[2024-11-04T13:38:05.202+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-04T13:38:05.202+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-04T13:38:05.202+0000] {logging_mixin.py:190} INFO - Current task name:save_data state:running start_date:2024-11-04 13:38:04.999420+00:00
[2024-11-04T13:38:05.202+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelamento and current dag run status:running
[2024-11-04T13:38:05.202+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T13:38:05.203+0000] {inaturalist_dag.py:165} INFO - No new observations to store.
[2024-11-04T13:38:05.203+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-04T13:38:05.211+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T13:38:05.211+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=get_inaturalist_data_atropelamento, task_id=save_data, run_id=scheduled__2024-11-04T12:30:00+00:00, execution_date=20241104T123000, start_date=20241104T133804, end_date=20241104T133805
[2024-11-04T13:38:05.218+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-04T13:38:05.219+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-04T13:38:05.219+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelamento queued_at:2024-11-04 13:37:53.756798+00:00
[2024-11-04T13:38:05.219+0000] {logging_mixin.py:190} INFO - Task hostname:d6bcfe968a2b operator:_PythonDecoratedOperator
[2024-11-04T13:38:05.243+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-04T13:38:05.262+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T13:38:05.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
